const ORDER_PENDING_STATUS_ID = 1;
const ORDER_PAID_STATUS_ID = 2;
const ORDER_ACCEPTED_STATUS_ID = 3;
const ORDER_COMPLETED_STATUS_ID = 4;
const ORDER_CANCELED_STATUS_ID = 5;

export {
    ORDER_PENDING_STATUS_ID,
    ORDER_PAID_STATUS_ID,
    ORDER_ACCEPTED_STATUS_ID,
    ORDER_COMPLETED_STATUS_ID,
    ORDER_CANCELED_STATUS_ID
};