const PAYMENT_PENDING_STATUS_ID = 1;
const PAYMENT_PAID_STATUS_ID = 2;
const PAYMENT_CANCELED_STATUS_ID = 3;

export {
    PAYMENT_PENDING_STATUS_ID,
    PAYMENT_PAID_STATUS_ID,
    PAYMENT_CANCELED_STATUS_ID
};